/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Head: typeof import('./src/components/Head.vue')['default']
    IEpArrowDown: typeof import('~icons/ep/arrow-down')['default']
    IEpCloseBold: typeof import('~icons/ep/close-bold')['default']
    IEpHelpFilled: typeof import('~icons/ep/help-filled')['default']
    IEpRank: typeof import('~icons/ep/rank')['default']
    IEpRemoveFilled: typeof import('~icons/ep/remove-filled')['default']
    SpeechPanel: typeof import('./src/components/SpeechPanel.vue')['default']
  }
}
