// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBiliFollower() {
  return window['go']['assistant']['Assistant']['GetBiliFollower']();
}

export function Startup(arg1) {
  return window['go']['assistant']['Assistant']['Startup'](arg1);
}
